apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hugo-test-project-poi-map-app-dev
  annotations:
    argocd/app-name: hugo-test-project-poi-map-app-dev
    backstage.io/kubernetes-id: hugo-test-project-poi-map-app
    backstage.io/kubernetes-namespace: hugo-test-project
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/hugo-test-project-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/hugo-test-project/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/hugo-test-project/deployments/hugo-test-project-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/hugo-test-project-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://hugo-test-project-poi-map-app-hugo-test-project.apps.kovj5vhc.eastus.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:hdmeyer"
  system: workshop-system-hugo-test-project
  consumesApis:
    - gateway-api-hugo-test-project
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hugo-test-project
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:hdmeyer"
